### ISSUE TITLE
Merging Databases between OpenJ9 and OMR

### ISSUE THREAD

**Issue by samasri** [samasri/omr#51]
When updating both databases together, I got some conflicts. This issue is to track how I am solving them.

# Conflicts
For example when adding queries from one table in OMR and the same table in OpenJ9, I would get different queries having the same IDs, since OMRStatistics is operating independently in each projects and starts the ID counter from 0 in both projects; so I end up having ID#1 linked to one record in OMR and for another project ID#1 would be linked to another record in OpenJ9. That was a general problem between most tables (**File** table, **Class** table, **Function** table, and **Hierarchy** table).
Other conflicts are reported below:
* When merging the **File** table: No other conflicts
* When merging the **Class** table:  (namespace, className) were being repeated between both projects, so I had to skip the records with duplicate (namespace, className). However, the records I am dropping are being referenced by records in the **Function** table. So I had to keep track of the class IDs I am dropping as duplicates in order to replace them with the right IDs when being referenced in the **Function** table.
* When merging the **Function** table: After replacing the duplicate Class IDs with the original ones, I got duplicate records that I removed. I also had to keep track of omitted function IDs, since they are being referenced in the **Override** table.
* When merging the **Override** table: Same as **Function** table processing, I replaced function IDs with their original ones based on my tracking of removed function IDs in the **Function** table. After that I removed duplicate records.

# Example
Consider the following example (from the OMR/OpenJ9 source code)

### In OMR
| ID | ClassName | Namespace | isExtensible |
| --- | --- | --- | --- |
| 469 | OMR | Linkage | 1 |
| 1345 | TR | S390zOSSystemLinkage | 0 |

### In OpenJ9
| ID | ClassName | Namespace | isExtensible |
| --- | --- | --- | --- |
| 1946 | OMR | Linkage | 1 |
| 2942 | TR | S390zOSSystemLinkage | 0 |

Here we have 2 examples of classes; each having 2 different IDs depending on if its being processed in OMR or OpenJ9. When merging both databases together, we will get an error that (className, Namespace) are being repeated.

### In OMR
| ID | Name | Signature | ClassID | isVirtual | isImplicit | FileID |
| --- | --- | --- | --- | --- | --- | --- |
| 13000 | isSpecialNonVolatileArgumentRegister | isSpecialNonVolatileArgumentRegister(int8_t) | 469 | 1 | 0 | 1216 |
| 29676 | isSpecialNonVolatileArgumentRegister | isSpecialNonVolatileArgumentRegister(int8_t) | 1345 | 1 | 0 | 1975 |

### In OpenJ9
| ID | Name | Signature | ClassID | isVirtual | isImplicit | FileID |
| --- | --- | --- | --- | --- | --- | --- |
| 46407 | isSpecialNonVolatileArgumentRegister | isSpecialNonVolatileArgumentRegister(int8_t) | 1946 | 1 | 0 | 59391 |
| 69010 | isSpecialNonVolatileArgumentRegister | isSpecialNonVolatileArgumentRegister(int8_t) | 2942 | 1 | 0 | 60138 |

Here, we have 2 examples of functions referencing the same class technically, however they are referencing different class IDs. The first function (first record in each table) is referencing the class `OMR::Linkage`, however since the last has different IDs in each project (shown in the description of problem 1), we are getting this error. Same for the second function (second record in each table) when referencing `TR::S390zOSSystemLinkage`.

### OMR
| BaseClassID | OverridingFunctionID |
| --- | ---|
| 13000 | 29676|

### OpenJ9
| BaseClassID | OverridingFunctionID |
| --- | ---|
| 46407| 69010|

Here, both records are implying that `OMR::Linkage::isSpecialNonVolatileArgumentRegister(int8_t)` is being overloaded by `TR::S390zOSSystemLinkage::isSpecialNonVolatileArgumentRegister(int8_t)`. However, due to the problems above, we are having 2 records.

# Task Summary
- [ ] Merge SQL databases with a python script
    * Errors are happening: for example classes are repeated between the omr and openj9 database.
    - [x] Merge File table
    - [x] Merge Class table
    - [x] Merge Function table
    - [x] Merge Override table
